<MyFlashcardsScreen>:
    BoxLayout:
        orientation: 'vertical'

        Button:
            text: 'Back'
            size_hint_y: None
            height: dp(50)
            on_release: app.change_screen('main')

        ScrollView:
            BoxLayout:
                id: folders_box
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
